### ISSUE TITLE
Token Privacy

### ISSUE THREAD

**Issue by sophiadt** [Xymoh/Discord-HuTao#1]
Hi! Nice Hu Tao discord bot. I noticed in your model_train_upload_workflow.ipynb file that you left your personal information in like your hugging face token. Just in case, I would reupload your colab file without this information in.

**Comment by Xymoh** [comment]
Thanks for pointing it out. Changed the file data and replaced it with placeholders, requested github stuff to delete the PR. Gonna definitely have to come back to that project now when AI is on hypertrain, but currently got occupied with stable diffusion.

**Comment by sophiadt** [comment]
Thanks for the quick reply. Yeah, AI is getting more and more popular now. Hope your Hu Tao bot and other AI progress goes well and good luck on your genshin pulls ✨
